spring:
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        tags: version=1.0,author=wany
  application:
    name: zuul
server:
  port: 8082